spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPOSITORY_URL} #https://github.com/pandaind/ecom-configs
          clone-on-start: true
          default-label: main
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS_URLS}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
